mysite/food/urls.py
from django.urls import path
from . import views

app_name='food'
urlpatterns = [
    path("",views.index,name='index'),
    path("<int:item_id>",views.detail,name='detail'),
    #add
    path("add",views.create_item,name='create_item'),
    #update
    path("update/<int:id>",views.update_item,name='update_item'),
    #delete
    path("delete/<int:id>",views.delete_item,name='delete_item')
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as authentication_views
from django.conf import settings
from django.conf.urls.static import static
# app_name='mysite'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("food.urls")),
    path('users/',include("users.urls")),
    path('login/',authentication_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',authentication_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),
    

]
urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/users/urls.py
from django.urls import path
from . import views

app_name='users'
urlpatterns = [
    path("register",views.register,name='register'),
    path('profile',views.profile,name='profile')
]

mysite/food/models.py
from django.db import models

# Create your models here.
class Item(models.Model):
    item_name=models.CharField(max_length=300)
    item_desc=models.CharField(max_length=300)
    item_price=models.IntegerField()
    item_image=models.CharField(max_length=500,default='https://www.treicamile.ro/wp-content/uploads/2021/11/food-placeholder.png')

    def __str__(self):
        return f"{self.item_name},{self.item_desc},{self.item_price}"
    class Meta:
        verbose_name=('Item name')

mysite/users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Profile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    image=models.ImageField(default='profilepic.jpg',upload_to='profile_pic')
    location=models.CharField(max_length=100)

    def __str__(self):
        return self.user.username

mysite/food/forms.py
from django import forms
from . models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model=Item
        fields=['item_name','item_price','item_desc','item_image']

mysite/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class RegisterForm(UserCreationForm):
    email=forms.EmailField()

    class Meta():
        model=User
        fields=['username','email','password1','password2']

mysite/food/views.py
from django.shortcuts import render,redirect
from . models import Item
from . forms import ItemForm
from django.http import HttpResponseRedirect

# Create your views here..
def index(request):
    item_list=Item.objects.all()
    return render(request,"food/index.html",{
        'item_list':item_list
    })

def detail(request,item_id):
    item=Item.objects.get(id=item_id)
    return render(request,"food/detail.html",{
        'item':item,
    })

def create_item(request):
    form=ItemForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('food:index')
    return  render(request,'food/Item-form.html',{
        'form':form
    })
def update_item(request,id):
    item=Item.objects.get(id=id)
    form=ItemForm(request.POST or None,instance=item)
    if form.is_valid():
        form.save()
        return redirect('food:index')
    return render(request,'food/Item-form.html',{
        'form':form,'item':item
    })

def delete_item(request,id):
    item=Item.objects.get(id=id)
    if request.method =="POST":
        item.delete()
        return redirect('food:index')
    return render(request,'food/item_delete.html',{
        'item':item
    })

mysite/users/views.py
from django.shortcuts import render,redirect
# from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from .forms import RegisterForm
from django.contrib.auth.decorators import login_required

# Create your views here.
def register(request):
    if request.method=="POST":
        form=RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username=form.cleaned_data.get('username')
            messages.success(request,f"Welcome, {username} ,your account is  craeted")
            return redirect('login')
    else:
        form=RegisterForm()
    return render(request,'users/register.html',{'form':form})

@login_required
def profile(request):
    return render(request,'users/profile.html')

mysite/food/templates/food/Item-form.html
{% extends 'food/base.html' %}

{% block body %}
    

    
<form action="" method="post">
{% csrf_token %}
{{form}}
<button type="submit" >save</button>

</form>
{% endblock body %}

mysite/food/templates/food/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous"></link>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">FoodApp</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'food:create_item' %}">Add Item</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Delete Item</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">View Item</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:profile' %}">Profile</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Login</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    

    
    {% if messages %}
    
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }}" role="alert">
        {{ message }}
    </div>
    
        
    {% endfor %}
        
        
    {% endif %}
        
    
    {% block body %}
        
    {% endblock body %}
        
</body>
</html>

mysite/food/templates/food/detail.html
{% extends 'food/base.html' %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img height="300px" src="{{ item.item_image }}" class="card-img-top" alt="{{ item.item_name }}">
        </div>
        <div class="col-md-6">
            <div class="card-body">
                <h1 class="card-title">{{ item.item_name }}</h1>
                <h2 class="card-text">{{ item.item_desc }}</h2>
                <h3 class="card-text">{{ item.item_price }}</h3>
                <a href="{% url 'food:delete_item' item.id %}">Delete</a>
            </div>
        </div>
    </div>
</div>

   

{% endblock body %}
    

mysite/food/templates/food/index.html
{% extends 'food/base.html' %}


{% block body %}
   
{% for item in item_list %}
<div class="row">
   <div class="col-md-3 offset-md-2">
       <img class="card-img-top" style="height: 150px;" src="{{ item.item_image }}" alt="{{ item.item_name }}">
   </div>
   <div class="col-md-4">
       <div class="card-body">
           <h3 class="card-title">{{ item.item_name }}</h3>
           <p class="card-text">{{ item.item_desc }}</p>
           <p class="card-text">{{ item.item_price }}</p>
       </div>
   </div>
   <div class="col-md-2">
      <a class="btn btn-success" href="{% url 'food:detail' item.id %}">Detail</a>

   </div>
</div>

   
{% endfor %}
{% endblock body %}

mysite/food/templates/food/item_delete.html
<form action="" method="post">
    {% csrf_token %}
    <h2>are you sure to delete the item {{item.item_name}}</h2>
    <button type="submit">Confirm</button>


</form>

mysite/users/templates/users/login.html
<form action="" method="post">
    {% csrf_token %}

      {{form}}{{form.error.name}}   
 <button type="submit">Login</button>
</form>

mysite/users/templates/users/logout.html
<h1>you have been logged out</h1>

mysite/users/templates/users/profile.html
<h1>{{user.username}}</h1>
<img src="{{user.profile.image.url}}" alt="" height="100px">

mysite/users/templates/users/register.html
<form action="" method="post">
    {% csrf_token %}
    {{form}}
    <button type="submit">SignUp</button>
</form>